name: Fetch Cyber Feeds

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: rss-update
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install feedparser requests

      - name: Fetch feeds
        run: python tools/fetch_feeds.py

      - name: Copy to docs if exists
        run: |
          if [ -d "docs" ]; then
            mkdir -p docs/feeds
            cp -f feeds/*.json docs/feeds/ || true
          fi

      - name: Commit & push JSON (with rebase)
        run: |
          set -e
          BRANCH="${GITHUB_REF_NAME:-main}"

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add feeds/*.json || true
          if [ -d "docs" ]; then git add docs/feeds/*.json || true; fi

          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -m "Update feeds JSON [skip ci]"

          git fetch origin "$BRANCH"
          git pull --rebase origin "$BRANCH" || (git rebase --abort && exit 1)

          git push origin "$BRANCH" || (sleep 3 && git pull --rebase origin "$BRANCH" && git push origin "$BRANCH")
