name: Fetch Cyber Feeds

on:
  schedule:
    - cron: "*/30 * * * *"   # every 30 minutes
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: rss-update
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install feedparser requests

      - name: Fetch feeds
        run: python tools/fetch_feeds.py

      - name: Copy to docs if exists
        run: |
          if [ -d "docs" ]; then
            mkdir -p docs/feeds
            cp -f feeds/*.json docs/feeds/ || true
          fi

      - name: Create PR with updates
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Update feeds JSON [skip ci]"
          title: "Update cyber feeds JSON"
          body: "Automated JSON refresh from Fetch Cyber Feeds workflow."
          branch: chore/update-feeds
          delete-branch: true
