name: Fetch Cyber Feeds

on:
  schedule:
    - cron: "*/30 * * * *"   # every 30 minutes
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Fetch feeds
        run: |
          python tools/fetch_feeds.py

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add feeds/*.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update feeds JSON [skip ci]"
            git push
          fi
